using UnityEngine;
public sealed class ReentryAudio {
 AudioSource wind,music,signal,wheels;bool wasRolling;AudioClip contact;AudioClip up,down;public bool Muted;
 public ReentryAudio(GameObject host){wind=host.AddComponent<AudioSource>();music=host.AddComponent<AudioSource>();signal=host.AddComponent<AudioSource>();wind.clip=Noise();wind.loop=true;wind.volume=0;wind.Play();music.clip=Pad();music.loop=true;music.volume=.16f;music.Play();up=CommandClip(true);down=CommandClip(false);wheels=host.AddComponent<AudioSource>();wheels.clip=Noise();wheels.loop=true;wheels.volume=0;wheels.Play();var samples=TouchdownSamples();contact=AudioClip.Create("Tire spin up",samples.Length,1,44100,false);contact.SetData(samples,0);}
 static AudioClip Noise(){int n=44100*3;float[] a=new float[n];var r=new System.Random(72);float smooth=0;for(int i=0;i<n;i++){smooth=Mathf.Lerp(smooth,(float)r.NextDouble()*2-1,.08f);a[i]=smooth*.6f*Mathf.Sin(Mathf.PI*i/(n-1));}var c=AudioClip.Create("Atmospheric friction",n,1,44100,false);c.SetData(a,0);return c;}
 static AudioClip Pad(){int n=44100*8;float[] a=new float[n];for(int i=0;i<n;i++){float t=i/44100f;float env=Mathf.Pow(Mathf.Sin(Mathf.PI*i/n),2);a[i]=env*(Mathf.Sin(t*2*Mathf.PI*110)*.1f+Mathf.Sin(t*2*Mathf.PI*164.81f)*.06f+Mathf.Sin(t*2*Mathf.PI*220)*.04f);}var c=AudioClip.Create("Orbital choir",n,1,44100,false);c.SetData(a,0);return c;}
 public void Tick(float heat,bool playing){signal.mute=Muted;wind.volume=Muted?0:playing?.08f+heat*.55f:0;wind.pitch=.6f+heat*1.3f;music.volume=Muted?0:playing?.13f:.22f;}
 public static float[] TouchdownSamples(){int n=17640;float[] a=new float[n];var rng=new System.Random(109);float low=0;for(int i=0;i<n;i++){float t=i/44100f,u=(float)i/n;low=Mathf.Lerp(low,(float)rng.NextDouble()*2-1,.18f);a[i]=(.10f*low+.09f*Mathf.Sin(2*Mathf.PI*(1450*t-1000*t*t)))*Mathf.Sin(Mathf.PI*u)*Mathf.Exp(-u*4);}return a;}
 public void Landing(LandingFrame? frame){bool rolling=frame.HasValue&&frame.Value.Stage>=LandingStage.Touchdown;if(rolling&&!wasRolling&&!Muted)signal.PlayOneShot(contact);wasRolling=rolling;float speed=rolling?(float)frame.Value.Speed:0;wheels.volume=Muted?0:Mathf.Clamp01(speed/70)*.28f;wheels.pitch=.35f+speed/90;}
 public static float[] CommandSamples(bool up){int n=4851;var data=new float[n];for(int i=0;i<n;i++){float t=i/44100f,u=(float)i/n;data[i]=Mathf.Sin(2*Mathf.PI*(up?380*t+900*t*t:580*t-900*t*t))*.085f*Mathf.Sin(Mathf.PI*u)*Mathf.Sin(Mathf.PI*u);}return data;}
 static AudioClip CommandClip(bool up){var data=CommandSamples(up);var clip=AudioClip.Create(up?"Nose servo up":"Nose servo down",data.Length,1,44100,false);clip.SetData(data,0);return clip;}
 public void Command(bool raised){if(!Muted)signal.PlayOneShot(raised?up:down);}
 public void Tone(bool success){int n=22050;float[] a=new float[n];for(int i=0;i<n;i++){float t=i/44100f;float hz=success?440+220*(i/(n/3)):145;a[i]=Mathf.Sin(t*hz*2*Mathf.PI)*.2f*Mathf.Sin(Mathf.PI*i/n);}var clip=AudioClip.Create("Telemetry acknowledgement",n,1,44100,false);clip.SetData(a,0);if(!Muted)signal.PlayOneShot(clip);Object.Destroy(clip,2);}
}
