using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
public sealed class ReentryWorld {
 public Camera Camera;public Transform Ship;Transform planet,atmosphere,runway;ParticleSystem sparks,stars;TrailRenderer[] trails=new TrailRenderer[5];Material ceramic;Light heatLight;float clock,endClock;LineRenderer[] plasma=new LineRenderer[9];Light sun;public bool ReduceMotion;
 static Material Mat(string shader,Color c){var m=new Material(Resources.Load<Material>(shader));m.SetColor("_BaseColor",c);return m;}
 static GameObject Primitive(string name,PrimitiveType type,Vector3 pos,Vector3 scale,Material material,Transform parent=null){var g=GameObject.CreatePrimitive(type);g.name=name;g.transform.SetParent(parent,false);g.transform.localPosition=pos;g.transform.localScale=scale;Object.Destroy(g.GetComponent<Collider>());g.GetComponent<Renderer>().sharedMaterial=material;return g;}
 public ReentryWorld(){
  var c=new GameObject("Flight camera");Camera=c.AddComponent<Camera>();Camera.fieldOfView=48;Camera.nearClipPlane=.1f;Camera.farClipPlane=3000;Camera.backgroundColor=new Color(.004f,.009f,.025f);Camera.clearFlags=CameraClearFlags.SolidColor;c.AddComponent<AudioListener>();Camera.GetUniversalAdditionalCameraData().renderPostProcessing=true;
  sun=new GameObject("Solar key").AddComponent<Light>();sun.type=LightType.Directional;sun.intensity=2.4f;sun.color=new Color(.83f,.91f,1);sun.transform.rotation=Quaternion.Euler(35,-35,0);RenderSettings.ambientMode=AmbientMode.Flat;RenderSettings.ambientLight=new Color(.21f,.27f,.36f);
  var fill=new GameObject("Earth bounce").AddComponent<Light>();fill.type=LightType.Directional;fill.color=new Color(.12f,.48f,1);fill.intensity=1;fill.transform.rotation=Quaternion.Euler(-30,160,0);
  var vol=new GameObject("Optical bloom").AddComponent<Volume>();vol.isGlobal=true;vol.profile=ScriptableObject.CreateInstance<VolumeProfile>();var bloom=vol.profile.Add<Bloom>();bloom.intensity.Override(.6f);bloom.threshold.Override(1);var vignette=vol.profile.Add<Vignette>();vignette.intensity.Override(.23f);vignette.smoothness.Override(.65f);var tone=vol.profile.Add<Tonemapping>();tone.mode.Override(TonemappingMode.ACES);
  planet=Primitive("Earth",PrimitiveType.Sphere,new Vector3(0,-530,150),Vector3.one*1000,Resources.Load<Material>("Planet")).transform;
  planet.GetComponent<MeshFilter>().sharedMesh=Globe();
  atmosphere=Primitive("Atmospheric limb",PrimitiveType.Sphere,planet.position,Vector3.one*1006,Mat("Atmosphere",new Color(.05f,.35f,1))).transform;
  atmosphere.GetComponent<MeshFilter>().sharedMesh=planet.GetComponent<MeshFilter>().sharedMesh;
  var asset=Resources.Load<GameObject>("Ember");Ship=Object.Instantiate(asset).transform;Ship.name="EMBER / Blender lifting body";
  foreach(var r in Ship.GetComponentsInChildren<Renderer>()){
   var mats=r.sharedMaterials;for(int i=0;i<mats.Length;i++){string n=mats[i]?mats[i].name:"";Color col=new Color(.75f,.81f,.85f);if(n.Contains("Carbon"))col=new Color(.025f,.034f,.047f);if(n.Contains("Titanium"))col=new Color(.2f,.28f,.35f);if(n.Contains("Cockpit"))col=new Color(.015f,.16f,.24f);if(n.Contains("Orange"))col=new Color(1,.16f,.025f);if(n.Contains("Cyan"))col=new Color(.03f,.8f,1);var m=Mat("Lit",col);m.SetFloat("_Metallic",n.Contains("Cockpit")?.8f:.25f);m.SetFloat("_Smoothness",n.Contains("Cockpit")?.9f:.45f);if(n.Contains("Cyan")){m.EnableKeyword("_EMISSION");m.SetColor("_EmissionColor",col*4);}mats[i]=m;if(n.Contains("Ceramic"))ceramic=m;}r.sharedMaterials=mats;
  }
  heatLight=new GameObject("Plasma illumination").AddComponent<Light>();heatLight.type=LightType.Point;heatLight.range=18;heatLight.color=new Color(1,.15f,.015f);heatLight.transform.position=new Vector3(0,-1,2);
  for(int j=0;j<9;j++){var g=new GameObject("Bow shock filament "+j);g.transform.SetParent(Ship,false);var line=g.AddComponent<LineRenderer>();line.useWorldSpace=false;line.positionCount=32;line.widthMultiplier=.3f;line.material=Mat("Plasma",new Color(1,.25f,.035f,.5f));line.numCapVertices=4;plasma[j]=line;}
  for(int i=0;i<5;i++){var g=new GameObject("Ionized wake "+i);g.transform.SetParent(Ship,false);g.transform.localPosition=new Vector3((i-2)*1.25f,-.2f,2.4f);var t=g.AddComponent<TrailRenderer>();t.time=1.2f;t.minVertexDistance=.08f;t.startWidth=i==2?1.3f:.55f;t.endWidth=0;t.material=Mat("Plasma",new Color(1,.15f,.025f,.8f));t.numCapVertices=3;trails[i]=t;}
  sparks=Particles("Ablative sparks",850,new Color(1,.32f,.04f),.045f);sparks.transform.SetParent(Ship,false);sparks.transform.localPosition=new Vector3(0,0,-3);var shape=sparks.shape;shape.shapeType=ParticleSystemShapeType.Cone;shape.angle=22;shape.radius=1.2f;sparks.transform.localRotation=Quaternion.identity;
  stars=Particles("Orbital starfield",450, new Color(.65f,.8f,1),.08f);var main=stars.main;main.startLifetime=10000;main.startSpeed=0;main.simulationSpace=ParticleSystemSimulationSpace.World;var emission=stars.emission;emission.rateOverTime=0;var particles=new ParticleSystem.Particle[400];var random=new System.Random(21);for(int i=0;i<particles.Length;i++){particles[i].position=new Vector3((float)random.NextDouble()*900-450,(float)random.NextDouble()*450+40,(float)random.NextDouble()*600-150);particles[i].startColor=new Color(.65f,.8f,1);particles[i].startSize=.25f+(float)random.NextDouble()*.7f;particles[i].remainingLifetime=10000;particles[i].startLifetime=10000;}stars.SetParticles(particles,particles.Length);
  var ground=Mat("Lit",new Color(.03f,.08f,.095f));runway=new GameObject("Aster landing complex").transform;runway.position=new Vector3(0,-35,70);Primitive("Coastal island",PrimitiveType.Cylinder,Vector3.zero,new Vector3(90,.6f,150),ground,runway);Primitive("Runway",PrimitiveType.Cube,new Vector3(0,.5f,0),new Vector3(7,.12f,100),Mat("Lit",new Color(.055f,.075f,.09f)),runway);
  var white=Mat("Unlit",new Color(.65f,.8f,.85f));var cyan=Mat("Unlit",new Color(.15f,2,3));for(int i=-12;i<=12;i++){Primitive("Center stripe",PrimitiveType.Cube,new Vector3(0,.58f,i*3.6f),new Vector3(.15f,.03f,1.4f),white,runway);foreach(int side in new[]{-1,1})Primitive("Approach light",PrimitiveType.Cube,new Vector3(side*3.9f,.75f,i*3.6f),new Vector3(.16f,.16f,.25f),cyan,runway);}
  for(int i=0;i<6;i++){Primitive("Service hangar",PrimitiveType.Cube,new Vector3(12+i%2*9,1.6f,-20+i*8),new Vector3(6,3,5),Mat("Lit",new Color(.2f,.27f,.3f)),runway);}Primitive("Control tower",PrimitiveType.Cube,new Vector3(-10,4,12),new Vector3(2,8,2),ground,runway);Primitive("Tower glazing",PrimitiveType.Cube,new Vector3(-10,8.5f,12),new Vector3(4,1.5f,3),cyan,runway);
 }
 ParticleSystem Particles(string name,int cap,Color color,float size){var p=new GameObject(name).AddComponent<ParticleSystem>();var m=p.main;m.maxParticles=cap;m.startLifetime=.65f;m.startSpeed=18;m.startSize=size;m.startColor=color;m.simulationSpace=ParticleSystemSimulationSpace.World;var e=p.emission;e.rateOverTime=0;var r=p.GetComponent<ParticleSystemRenderer>();r.material=Mat("Unlit",color);return p;}
 public void Tick(FlightModel f,bool playing,bool ended,float dt){clock+=dt;if(ended)endClock+=dt;else endClock=0;float alt=f==null?80:f.Altitude;float heat=f==null?0:f.Heat;float attack=f==null?.28f:f.Attack;
  float stage=1-alt/80;int mission=f?.Mission??0;sun.color=mission==2?new Color(.3f,.5f,1):mission==1?new Color(1,.6f,.35f):new Color(.83f,.91f,1);sun.intensity=mission==2?1.1f:2.1f;planet.Rotate(0,dt*.16f,0);planet.position=new Vector3(0,Mathf.Lerp(-535,-502,stage),150);atmosphere.position=planet.position;
  runway.gameObject.SetActive(alt<28);runway.position=new Vector3(0,Mathf.Lerp(-35,-2,1-alt/80),Mathf.Lerp(75,0,Mathf.Pow(stage,3)));
  Vector3 position=new Vector3(Mathf.Sin(clock*.35f)*.2f,Mathf.Sin(clock*.7f)*.1f,-clock*12); // camera travels with craft; wake gets real motion
  if(ended&&f.Outcome==FlightOutcome.Landed)position.y-=Mathf.SmoothStep(0,.65f,Mathf.Clamp01(endClock/3));
  Ship.position=position;planet.position+=new Vector3(0,0,position.z);atmosphere.position=planet.position;runway.position+=new Vector3(0,0,position.z);
  Ship.rotation=Quaternion.Euler(ended?Mathf.Lerp(15,0,Mathf.Clamp01(endClock/2)):Mathf.Lerp(4,31,attack),0,Mathf.Sin(clock*.5f)*(ReduceMotion?.6f:2.5f));
  float intensity=playing?Mathf.Clamp01(heat*1.4f+.06f):0;heatLight.transform.position=position+new Vector3(0,-.5f,3);heatLight.intensity=intensity*14;
  for(int j=0;j<plasma.Length;j++){var line=plasma[j];line.enabled=intensity>.16f&&!ended;float angle=j*Mathf.PI*2/9;line.widthMultiplier=.16f+intensity*.24f;line.startColor=new Color(1,.55f,.15f,intensity*.75f);line.endColor=new Color(1,.07f,.02f,0);for(int k=0;k<32;k++){float u=k/31f;float radius=.3f+Mathf.Sin(u*Mathf.PI*.65f)*2.9f;float ripple=Mathf.Sin(u*20-clock*16+j)*u*.16f;line.SetPosition(k,new Vector3(Mathf.Cos(angle)*(radius+ripple),Mathf.Sin(angle)*radius*.3f-.12f,-3.7f+u*13));}}
  var e=sparks.emission;e.rateOverTime=ended?0:intensity*350;var m=sparks.main;m.startSpeed=15+intensity*30;
  foreach(var trail in trails){trail.emitting=playing&&!ended&&heat>.14f;trail.startColor=Color.Lerp(new Color(.2f,.55f,1,.2f),new Color(1,.28f,.04f,1),heat);trail.endColor=new Color(1,.05f,0,0);}
  float shake=ReduceMotion?0:Mathf.Pow(Mathf.Max(0,heat-.4f),2)*.18f;Vector3 offset=(playing||ended)?new Vector3(10,5.8f,-14):new Vector3(10,6,-13);if(alt<14&&playing)offset=Vector3.Lerp(offset,new Vector3(8,4,-12),1-alt/14);
  Camera.transform.position=position+offset+new Vector3(Mathf.Sin(clock*29),Mathf.Cos(clock*33),0)*shake;Camera.transform.LookAt(position+((playing||ended)?new Vector3(-1,0,1):-Vector3.Cross(Vector3.up,-offset.normalized)*6));Camera.fieldOfView=Mathf.Lerp(Camera.fieldOfView,playing?50+heat*6:43,dt*2);
 }
 static Mesh Globe(){int rows=96,cols=192;var v=new Vector3[(rows+1)*(cols+1)];var normals=new Vector3[v.Length];var indices=new int[rows*cols*6];int k=0;for(int y=0;y<=rows;y++)for(int x=0;x<=cols;x++){float a=Mathf.PI*y/rows,b=Mathf.PI*2*x/cols;var n=new Vector3(Mathf.Sin(a)*Mathf.Cos(b),Mathf.Cos(a),Mathf.Sin(a)*Mathf.Sin(b));v[y*(cols+1)+x]=n*.5f;normals[y*(cols+1)+x]=n;if(y<rows&&x<cols){int i=y*(cols+1)+x;indices[k++]=i;indices[k++]=i+1;indices[k++]=i+cols+1;indices[k++]=i+1;indices[k++]=i+cols+2;indices[k++]=i+cols+1;}}var m=new Mesh();m.vertices=v;m.normals=normals;m.triangles=indices;m.RecalculateBounds();return m;}
 public void Burst(){sparks.Emit(240);}
}
